Submitting a proposed fix for the timer too close issue from #382.
intelligent-agent/Refactor pull request #383
Opened 2023-09-27 07:12 UTC by goeland86

This has been shown to work on A6 and A7 boards.

However, it does force the main CPUs of the A64 to run at full throttle all the time. This may not be feasible on printers without adequate cooling of the electronics.

There is the option of setting parameters using the user-space governor and manually selecting a frequency that keeps the system stable, but this hasn't yet been done.

2023-09-27 15:23 UTC, eliasbakken requested changes

2023-09-27 15:23 UTC, eliasbakken commented on roles/install_klipper/files/ar100.config
I don't think there should be any changes to the Klipper config files in order to make this PR pass.

2023-09-27 15:56 UTC, goeland86 commented on roles/install_klipper/files/ar100.config
There have been updates to the Klipper MCU code that make it so large that if you update to the latest Klipper and don't disable certain MCU features baked in, you exceed the allocated memory of the MCU. So, yes, I added those in.

2023-10-26 21:40 UTC, eliasbakken approved these changes

2023-10-27 11:06 UTC, merged